import { KanbanColumn as KanbanColumnType } from '@/widgets/kanban/types/kanban';

export const initialColumns: KanbanColumnType[] = [
  {
    id: 'todo',
    title: 'To do',
    tasks: [
      {
        id: '1',
        title: 'Request new HACCP',
        description: 'BG-73',
        progress: 0,
        columnId: 0,
        difficulty: 'medium',
        topics: ['HACCP'],
        commentsCount: 0,
        filesCount: 0,
        done: false,
      },
      {
        id: '2',
        title: 'Collect and verify supplier information',
        description: 'BG-79',
        progress: 0,
        columnId: 0,
        difficulty: 'easy',
        topics: ['Supplier'],
        commentsCount: 0,
        filesCount: 0,
        done: false,
      },
      {
        id: '3',
        title: 'IFS',
        description: 'BG-76',
        progress: 0,
        columnId: 0,
        difficulty: 'hard',
        topics: ['IFS'],
        commentsCount: 0,
        filesCount: 0,
        done: false,
      },
    ],
  },
  {
    id: 'inprogress',
    title: 'In progress',
    tasks: [
      {
        id: '4',
        title: 'Get new HACCP from LM Farm',
        description: 'BG-68',
        progress: 60,
        columnId: 0,
        difficulty: 'medium',
        topics: ['HACCP', 'Supplier'],
        commentsCount: 3,
        filesCount: 1,
        done: false,
      },
      {
        id: '5',
        title: 'Investigate quality issues (ACS)',
        description: 'BG-65',
        progress: 30,
        columnId: 0,
        difficulty: 'hard',
        topics: ['Quality', 'ACS'],
        commentsCount: 4,
        filesCount: 2,
        done: false,
      },
      {
        id: '6',
        title: 'Confirm production schedule for Q3',
        description: 'BG-66',
        progress: 100,
        columnId: 0,
        difficulty: 'medium',
        topics: ['Production'],
        commentsCount: 0,
        filesCount: 0,
        done: true,
      },
      {
        id: '7',
        title: 'Digitalize reports 2023',
        description: 'BG-63',
        progress: 80,
        columnId: 0,
        difficulty: 'easy',
        topics: ['Reports'],
        commentsCount: 3,
        filesCount: 0,
        done: false,
      },
    ],
  },
  {
    id: 'completed',
    title: 'Completed',
    tasks: [
      {
        id: '8',
        title: 'Internal security audit - Q3',
        description: 'BG-54',
        progress: 100,
        columnId: 0,
        difficulty: 'hard',
        topics: ['Audit'],
        commentsCount: 7,
        filesCount: 0,
        done: true,
      },
      {
        id: '9',
        title: 'Request new HACCP',
        description: 'BG-47',
        progress: 100,
        columnId: 0,
        difficulty: 'medium',
        topics: ['HACCP'],
        commentsCount: 3,
        filesCount: 0,
        done: true,
      },
      {
        id: '10',
        title: 'Collect and verify supplier information',
        description: 'BG-53',
        progress: 100,
        columnId: 0,
        difficulty: 'easy',
        topics: ['Supplier'],
        commentsCount: 0,
        filesCount: 0,
        done: true,
      },
    ],
  },
];
